In [5]:
import pandas as pd

file_path = "E:\Hospital Project\Hospital_Management_Dataset.xlsx"

xls = pd.ExcelFile("E:\Hospital Project\Hospital_Management_Dataset.xlsx")

print(xls.sheet_names)

['patients', 'appointments', 'admissions', 'billing', 'lab_tests', 'prescriptions', 'doctors', 'departments', 'rooms', 'medicines']

In [6]:
tables = {
    sheet: pd.read_excel(file_path, sheet_name=sheet)
    for sheet in xls.sheet_names
}

print(tables.keys())

dict_keys(['patients', 'appointments', 'admissions', 'billing', 'lab_tests', 'prescriptions', 'doctors', 'departments', 'rooms', 'medicines'])

In [7]:
for name, df in tables.items():
    print("\n====================")
    print(name.upper())
    print("====================")
    display(df.head())

====================
PATIENTS
====================

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,marital_status,city,state,phone,email,insurance_provider,registration_date
0,P00001,Chloe,Williams,Female,1991-01-02,34,O+,Married,Springfield,Northvale,+1-555-507-4059,chloe.williams574@example.com,UnitedCare,2022-06-03
1,P00002,Victor,Wilson,Male,2007-10-27,18,A+,Married,Ashford,Westfield,+1-555-630-1101,victor.wilson289@example.com,Self-Pay,2023-08-16
2,P00003,Mei,Green,Female,1991-05-04,34,O+,Single,Clifton,Southgate,+1-555-357-4543,mei.green662@example.com,BlueShield Health,2020-01-05
3,P00004,Jennifer,Costa,Female,2022-05-13,3,O+,Single,Clifton,Southgate,+1-555-559-3453,jennifer.costa71@example.com,Aetna Plus,2020-08-02
4,P00005,Sarah,Kim,Female,1997-10-21,28,O+,Married,Georgetown,Westfield,+1-555-483-7525,sarah.kim88@example.com,UnitedCare,2025-03-08

====================
APPOINTMENTS
====================

,appointment_id,patient_id,doctor_id,department_id,appointment_date,appointment_time,appointment_type,status,wait_time_min,consultation_fee,diagnosis,satisfaction_rating
0,A00001,P02187,DR068,D07,2024-01-01,09:30,New,Cancelled,NaN,0.0,NaN,NaN
1,A00002,P02047,DR077,D08,2024-01-01,09:30,New,Completed,23.0,108.0,Sleep Apnea,5.0
2,A00003,P02942,DR024,D10,2024-01-01,10:00,Follow-up,Completed,12.0,190.0,Breast Cancer,5.0
3,A00004,P02401,DR015,D01,2024-01-01,10:30,New,Completed,63.0,67.0,Typhoid,4.0
4,A00005,P02499,DR054,D03,2024-01-01,11:30,Follow-up,Completed,29.0,168.0,Heart Failure,5.0

====================
ADMISSIONS
====================

,admission_id,patient_id,doctor_id,department_id,room_id,admission_date,discharge_date,length_of_stay,admission_type,diagnosis,discharge_status,readmitted_within_30d
0,ADM00001,P02500,DR020,D01,R011,2024-01-01,2024-01-03,2,Emergency,Type 2 Diabetes,Referred,No
1,ADM00002,P02231,DR068,D07,R005,2024-01-02,2024-01-05,3,Elective,Hepatitis,Recovered,No
2,ADM00003,P01594,DR041,D10,R100,2024-01-02,2024-01-15,13,Transfer,Lung Cancer,Recovered,No
3,ADM00004,P01689,DR078,D02,R046,2024-01-03,2024-01-10,7,Elective,Allergic Reaction,Recovered,No
4,ADM00005,P02755,DR077,D08,R049,2024-01-03,2024-01-05,2,Transfer,Asthma,Recovered,No

====================
BILLING
====================

,bill_id,patient_id,appointment_id,admission_id,bill_date,bill_type,consultation_charges,room_charges,lab_charges,medicine_charges,procedure_charges,total_amount,insurance_covered,patient_payable,payment_status,payment_method,insurance_provider
0,B00001,P02047,A00002,NaN,2024-01-01,OPD,108.0,0.0,0.00,0.00,0.0,108.0,0.00,108.00,Partially Paid,Card,BlueShield Health
1,B00002,P02942,A00003,NaN,2024-01-01,OPD,190.0,0.0,0.00,5688.20,0.0,5878.2,3412.14,2466.06,Paid,Card,UnitedCare
2,B00003,P02401,A00004,NaN,2024-01-01,OPD,67.0,0.0,0.00,44.10,0.0,111.1,55.45,55.65,Paid,Insurance Settlement,Cigna Care
3,B00004,P02499,A00005,NaN,2024-01-01,OPD,168.0,0.0,0.00,0.00,0.0,168.0,53.28,114.72,Paid,Insurance Settlement,Aetna Plus
4,B00005,P03028,A00006,NaN,2024-01-01,OPD,67.0,0.0,55.17,579.03,0.0,701.2,425.32,275.88,Paid,Cash,UnitedCare

====================
LAB_TESTS
====================

,lab_test_id,patient_id,doctor_id,appointment_id,admission_id,test_name,test_category,test_date,test_cost,result_status,turnaround_hours
0,L00001,P01149,DR010,A00012,NaN,Troponin I,Cardiology,2024-01-01,61.10,Abnormal,14
1,L00002,P00550,DR040,A00011,NaN,ECG,Cardiology,2024-01-01,29.37,Normal,10
2,L00003,P00397,DR048,A00010,NaN,Vitamin D,Biochemistry,2024-01-01,64.45,Abnormal,7
3,L00004,P03028,DR015,A00006,NaN,Vitamin D,Biochemistry,2024-01-01,55.17,Normal,9
4,L00005,P00397,DR048,A00010,NaN,Urine Routine,Pathology,2024-01-01,14.79,Abnormal,24

====================
PRESCRIPTIONS
====================

,prescription_id,patient_id,doctor_id,appointment_id,admission_id,medicine_id,dosage,frequency,duration_days,quantity,prescribed_date
0,RX00001,P00397,DR048,A00010,NaN,M011,500 mg,Twice daily,5,10,2024-01-01
1,RX00002,P01452,DR058,A00008,NaN,M027,20 mg,Once daily,3,3,2024-01-01
2,RX00003,P01149,DR010,A00012,NaN,M046,250 mg,Twice daily,7,14,2024-01-01
3,RX00004,P02401,DR015,A00004,NaN,M051,500 mg,Twice daily,7,14,2024-01-01
4,RX00005,P02942,DR024,A00003,NaN,M061,5 mg,Thrice daily,10,30,2024-01-01

====================
DOCTORS
====================

,doctor_id,doctor_name,gender,department_id,specialization,qualification,experience_years,consultation_fee,join_date,status
0,DR001,Dr. James Nguyen,Male,D08,Pulmonology,"MBBS, MD",10,105.00,2017-08-25,Active
1,DR002,Dr. Maria Lopez,Female,D07,Gastroenterology,"MBBS, DM",8,107.67,2022-08-27,Active
2,DR003,Dr. Raj Lee,Male,D05,Pediatrics,"MBBS, MD, DNB",13,85.17,2015-04-04,Active
3,DR004,Dr. Raj Adams,Male,D05,Pediatrics,"MBBS, MD",2,72.33,2022-06-17,Active
4,DR005,Dr. Rahul Patel,Male,D03,Cardiology,"MBBS, DM",4,128.00,2023-05-22,Active

====================
DEPARTMENTS
====================

  department_id   department_name  floor  annual_budget head_doctor_id
0           D01  General Medicine      1        2400000          DR040
1           D02         Emergency      0        3800000          DR029
2           D03        Cardiology      3        4200000          DR054
3           D04       Orthopedics      2        3100000          DR009
4           D05        Pediatrics      1        1900000          DR075

====================
ROOMS
====================

  room_id     room_type  floor  daily_rate  capacity
0    R001  General Ward      3       93.73         6
1    R002  General Ward      5       91.58         6
2    R003  General Ward      4       83.92         6
3    R004  General Ward      2       90.03         6
4    R005  General Ward      1       93.80         6

====================
MEDICINES
====================

  medicine_id  medicine_name    category  unit_price manufacturer
0        M001    Amoxicillin  Antibiotic       18.24          GSK
1        M002   Azithromycin  Antibiotic        8.69        Zydus
2        M003  Ciprofloxacin  Antibiotic        9.97     Novartis
3        M004       Cefixime  Antibiotic       15.83        Lupin
4        M005    Doxycycline  Antibiotic        4.01       Pfizer

In [8]:
 for name, df in tables.items():
    print("\n====================")
    print(name.upper())
    print("====================")
    df.info()

====================
PATIENTS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          3400 non-null   object
 1   first_name          3400 non-null   object
 2   last_name           3400 non-null   object
 3   gender              3400 non-null   object
 4   date_of_birth       3400 non-null   datetime64[ns]
 5   age                 3400 non-null   int64
 6   blood_group         3337 non-null   object
 7   marital_status      3358 non-null   object
 8   city                3400 non-null   object
 9   state               3400 non-null   object
 10  phone               3400 non-null   object
 11  email               3254 non-null   object
 12  insurance_provider  3400 non-null   object
 13  registration_date   3400 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(11)
memory usage: 372.0+ KB

====================
APPOINTMENTS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   appointment_id       5500 non-null   object
 1   patient_id           5500 non-null   object
 2   doctor_id            5500 non-null   object
 3   department_id        5500 non-null   object
 4   appointment_date     5500 non-null   datetime64[ns]
 5   appointment_time     5500 non-null   object
 6   appointment_type     5500 non-null   object
 7   status               5500 non-null   object
 8   wait_time_min        4116 non-null   float64
 9   consultation_fee     5500 non-null   float64
 10  diagnosis            4116 non-null   object
 11  satisfaction_rating  3339 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(8)
memory usage: 515.8+ KB

====================
ADMISSIONS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   admission_id           2000 non-null   object
 1   patient_id             2000 non-null   object
 2   doctor_id              2000 non-null   object
 3   department_id          2000 non-null   object
 4   room_id                2000 non-null   object
 5   admission_date         2000 non-null   datetime64[ns]
 6   discharge_date         2000 non-null   datetime64[ns]
 7   length_of_stay         2000 non-null   int64
 8   admission_type         2000 non-null   object
 9   diagnosis              2000 non-null   object
 10  discharge_status       2000 non-null   object
 11  readmitted_within_30d  2000 non-null   object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 187.6+ KB

====================
BILLING
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   bill_id               6116 non-null   object
 1   patient_id            6116 non-null   object
 2   appointment_id        4116 non-null   object
 3   admission_id          2000 non-null   object
 4   bill_date             6116 non-null   datetime64[ns]
 5   bill_type             6116 non-null   object
 6   consultation_charges  6116 non-null   float64
 7   room_charges          6116 non-null   float64
 8   lab_charges           6116 non-null   float64
 9   medicine_charges      6116 non-null   float64
 10  procedure_charges     6116 non-null   float64
 11  total_amount          6116 non-null   float64
 12  insurance_covered     6116 non-null   float64
 13  patient_payable       6116 non-null   float64
 14  payment_status        6116 non-null   object
 15  payment_method        6116 non-null   object
 16  insurance_provider    6116 non-null   object
dtypes: datetime64[ns](1), float64(8), object(8)
memory usage: 812.4+ KB

====================
LAB_TESTS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lab_test_id       3500 non-null   object
 1   patient_id        3500 non-null   object
 2   doctor_id         3500 non-null   object
 3   appointment_id    2380 non-null   object
 4   admission_id      1120 non-null   object
 5   test_name         3500 non-null   object
 6   test_category     3500 non-null   object
 7   test_date         3500 non-null   datetime64[ns]
 8   test_cost         3500 non-null   float64
 9   result_status     3500 non-null   object
 10  turnaround_hours  3500 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 300.9+ KB

====================
PRESCRIPTIONS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   prescription_id  3800 non-null   object
 1   patient_id       3800 non-null   object
 2   doctor_id        3800 non-null   object
 3   appointment_id   3040 non-null   object
 4   admission_id     760 non-null    object
 5   medicine_id      3800 non-null   object
 6   dosage           3800 non-null   object
 7   frequency        3800 non-null   object
 8   duration_days    3800 non-null   int64
 9   quantity         3800 non-null   int64
 10  prescribed_date  3800 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 326.7+ KB

====================
DOCTORS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         80 non-null     object
 1   doctor_name       80 non-null     object
 2   gender            80 non-null     object
 3   department_id     80 non-null     object
 4   specialization    80 non-null     object
 5   qualification     80 non-null     object
 6   experience_years  80 non-null     int64
 7   consultation_fee  80 non-null     float64
 8   join_date         80 non-null     datetime64[ns]
 9   status            80 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 6.4+ KB

====================
DEPARTMENTS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    12 non-null     object
 1   department_name  12 non-null     object
 2   floor            12 non-null     int64
 3   annual_budget    12 non-null     int64
 4   head_doctor_id   12 non-null     object
dtypes: int64(2), object(3)
memory usage: 612.0+ bytes

====================
ROOMS
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   room_id     150 non-null    object
 1   room_type   150 non-null    object
 2   floor       150 non-null    int64
 3   daily_rate  150 non-null    float64
 4   capacity    150 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 6.0+ KB

====================
MEDICINES
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   medicine_id    63 non-null     object
 1   medicine_name  63 non-null     object
 2   category       63 non-null     object
 3   unit_price     63 non-null     float64
 4   manufacturer   63 non-null     object
dtypes: float64(1), object(4)
memory usage: 2.6+ KB

In [11]:
for name, df in tables.items():
    print("\n====================")
    print(name.upper())
    print("====================")
    print(df.isnull().sum())

====================
PATIENTS
====================
patient_id              0
first_name              0
last_name               0
gender                  0
date_of_birth           0
age                     0
blood_group            63
marital_status         42
city                    0
state                   0
phone                   0
email                 146
insurance_provider      0
registration_date       0
dtype: int64

====================
APPOINTMENTS
====================
appointment_id            0
patient_id                0
doctor_id                 0
department_id             0
appointment_date          0
appointment_time          0
appointment_type          0
status                    0
wait_time_min          1384
consultation_fee          0
diagnosis              1384
satisfaction_rating    2161
dtype: int64

====================
ADMISSIONS
====================
admission_id             0
patient_id               0
doctor_id                0
department_id            0
room_id                  0
admission_date           0
discharge_date           0
length_of_stay           0
admission_type           0
diagnosis                0
discharge_status         0
readmitted_within_30d    0
dtype: int64

====================
BILLING
====================
bill_id                    0
patient_id                 0
appointment_id          2000
admission_id            4116
bill_date                  0
bill_type                  0
consultation_charges       0
room_charges               0
lab_charges                0
medicine_charges           0
procedure_charges          0
total_amount               0
insurance_covered          0
patient_payable            0
payment_status             0
payment_method             0
insurance_provider         0
dtype: int64

====================
LAB_TESTS
====================
lab_test_id            0
patient_id             0
doctor_id              0
appointment_id      1120
admission_id        2380
test_name              0
test_category          0
test_date              0
test_cost              0
result_status          0
turnaround_hours       0
dtype: int64

====================
PRESCRIPTIONS
====================
prescription_id       0
patient_id            0
doctor_id             0
appointment_id      760
admission_id       3040
medicine_id           0
dosage                0
frequency             0
duration_days         0
quantity              0
prescribed_date       0
dtype: int64

====================
DOCTORS
====================
doctor_id           0
doctor_name         0
gender              0
department_id       0
specialization      0
qualification       0
experience_years    0
consultation_fee    0
join_date           0
status              0
dtype: int64

====================
DEPARTMENTS
====================
department_id      0
department_name    0
floor              0
annual_budget      0
head_doctor_id     0
dtype: int64

====================
ROOMS
====================
room_id       0
room_type     0
floor         0
daily_rate    0
capacity      0
dtype: int64

====================
MEDICINES
====================
medicine_id      0
medicine_name    0
category         0
unit_price       0
manufacturer     0
dtype: int64

In [12]:
for name, df in tables.items():
    print(name, "→", df.duplicated().sum(), "duplicate rows")

patients → 0 duplicate rows
appointments → 0 duplicate rows
admissions → 0 duplicate rows
billing → 0 duplicate rows
lab_tests → 0 duplicate rows
prescriptions → 0 duplicate rows
doctors → 0 duplicate rows
departments → 0 duplicate rows
rooms → 0 duplicate rows
medicines → 0 duplicate rows

In [13]:
for name, df in tables.items():
    print("\n====================")
    print(name.upper())
    print("====================")
    print(df.columns.tolist())

====================
PATIENTS
====================
['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'age', 'blood_group', 'marital_status', 'city', 'state', 'phone', 'email', 'insurance_provider', 'registration_date']

====================
APPOINTMENTS
====================
['appointment_id', 'patient_id', 'doctor_id', 'department_id', 'appointment_date', 'appointment_time', 'appointment_type', 'status', 'wait_time_min', 'consultation_fee', 'diagnosis', 'satisfaction_rating']

====================
ADMISSIONS
====================
['admission_id', 'patient_id', 'doctor_id', 'department_id', 'room_id', 'admission_date', 'discharge_date', 'length_of_stay', 'admission_type', 'diagnosis', 'discharge_status', 'readmitted_within_30d']

====================
BILLING
====================
['bill_id', 'patient_id', 'appointment_id', 'admission_id', 'bill_date', 'bill_type', 'consultation_charges', 'room_charges', 'lab_charges', 'medicine_charges', 'procedure_charges', 'total_amount', 'insurance_covered', 'patient_payable', 'payment_status', 'payment_method', 'insurance_provider']

====================
LAB_TESTS
====================
['lab_test_id', 'patient_id', 'doctor_id', 'appointment_id', 'admission_id', 'test_name', 'test_category', 'test_date', 'test_cost', 'result_status', 'turnaround_hours']

====================
PRESCRIPTIONS
====================
['prescription_id', 'patient_id', 'doctor_id', 'appointment_id', 'admission_id', 'medicine_id', 'dosage', 'frequency', 'duration_days', 'quantity', 'prescribed_date']

====================
DOCTORS
====================
['doctor_id', 'doctor_name', 'gender', 'department_id', 'specialization', 'qualification', 'experience_years', 'consultation_fee', 'join_date', 'status']

====================
DEPARTMENTS
====================
['department_id', 'department_name', 'floor', 'annual_budget', 'head_doctor_id']

====================
ROOMS
====================
['room_id', 'room_type', 'floor', 'daily_rate', 'capacity']

====================
MEDICINES
====================
['medicine_id', 'medicine_name', 'category', 'unit_price', 'manufacturer']

In [14]:
for name, df in tables.items():
    print(name, "→ Rows:", df.shape[0], "| Columns:", df.shape[1])

patients → Rows: 3400 | Columns: 14
appointments → Rows: 5500 | Columns: 12
admissions → Rows: 2000 | Columns: 12
billing → Rows: 6116 | Columns: 17
lab_tests → Rows: 3500 | Columns: 11
prescriptions → Rows: 3800 | Columns: 11
doctors → Rows: 80 | Columns: 10
departments → Rows: 12 | Columns: 5
rooms → Rows: 150 | Columns: 5
medicines → Rows: 63 | Columns: 5

In [15]:
for name, df in tables.items():
    print(name, "→ Rows:", df.shape[0], "| Columns:", df.shape[1])

patients → Rows: 3400 | Columns: 14
appointments → Rows: 5500 | Columns: 12
admissions → Rows: 2000 | Columns: 12
billing → Rows: 6116 | Columns: 17
lab_tests → Rows: 3500 | Columns: 11
prescriptions → Rows: 3800 | Columns: 11
doctors → Rows: 80 | Columns: 10
departments → Rows: 12 | Columns: 5
rooms → Rows: 150 | Columns: 5
medicines → Rows: 63 | Columns: 5

In [16]:
for name, df in tables.items():
    print("\n====================")
    print(name.upper())
    print("====================")
    display(df.describe())

====================
PATIENTS
====================

,date_of_birth,age,registration_date
count,3400,3400.000000,3400
mean,1986-06-02 08:12:33.882352896,39.089706,2022-11-22 03:51:14.823529216
min,1930-01-25 00:00:00,0.000000,2020-01-01 00:00:00
25%,1972-11-05 18:00:00,26.000000,2021-06-03 18:00:00
50%,1984-12-04 12:00:00,41.000000,2022-12-04 00:00:00
75%,1999-04-17 06:00:00,53.000000,2024-04-30 00:00:00
max,2025-12-28 00:00:00,95.000000,2025-09-30 00:00:00
std,NaN,20.674843,NaN

====================
APPOINTMENTS
====================

,appointment_date,wait_time_min,consultation_fee,satisfaction_rating
count,5500,4116.000000,5500.000000,3339.000000
mean,2025-02-23 11:05:16.800000,26.386297,84.550635,4.037736
min,2024-01-01 00:00:00,3.000000,0.000000,1.000000
25%,2024-09-09 00:00:00,13.000000,0.000000,4.000000
50%,2025-03-18 00:00:00,22.500000,89.830000,4.000000
75%,2025-08-26 06:00:00,36.000000,121.500000,5.000000
max,2025-12-31 00:00:00,140.000000,222.500000,5.000000
std,NaN,17.621798,57.650683,0.769639

====================
ADMISSIONS
====================

,admission_date,discharge_date,length_of_stay
count,2000,2000,2000.000000
mean,2025-02-26 07:36:28.800000,2025-03-03 10:40:04.799999744,5.127500
min,2024-01-01 00:00:00,2024-01-03 00:00:00,1.000000
25%,2024-09-10 00:00:00,2024-09-15 00:00:00,2.000000
50%,2025-03-18 00:00:00,2025-03-23 00:00:00,4.000000
75%,2025-09-05 00:00:00,2025-09-10 00:00:00,7.000000
max,2025-12-31 00:00:00,2026-01-17 00:00:00,36.000000
std,NaN,NaN,4.096784

====================
BILLING
====================

,bill_date,consultation_charges,room_charges,lab_charges,medicine_charges,procedure_charges,total_amount,insurance_covered,patient_payable
count,6116,6116.000000,6116.000000,6116.000000,6116.000000,6116.000000,6116.000000,6116.000000,6116.000000
mean,2025-02-25 23:03:01.294963968,213.289635,423.636501,94.125803,214.339552,437.813594,1383.205036,686.964274,696.240788
min,2024-01-01 00:00:00,63.000000,0.000000,0.000000,0.000000,0.000000,63.000000,0.000000,19.560000
25%,2024-09-11 00:00:00,96.000000,0.000000,0.000000,0.000000,0.000000,162.920000,22.377500,92.520000
50%,2025-03-20 00:00:00,129.000000,0.000000,34.440000,81.830000,0.000000,352.105000,99.440000,195.490000
75%,2025-08-30 06:00:00,223.085000,341.177500,103.045000,250.995000,0.000000,1362.437500,460.030000,562.187500
max,2026-01-17 00:00:00,1112.500000,23241.400000,2175.520000,17444.460000,25648.920000,30238.430000,25057.520000,21173.610000
std,NaN,199.055142,1343.264343,168.144316,524.741267,1320.955565,2597.399825,1657.420028,1504.565211

====================
LAB_TESTS
====================

                           test_date    test_cost  turnaround_hours
count                           3500  3500.000000       3500.000000
mean   2025-02-26 19:01:18.171428608    93.953609         14.700857
min              2024-01-01 00:00:00     8.040000          1.000000
25%              2024-09-08 00:00:00    28.890000          8.000000
50%              2025-03-20 12:00:00    44.885000         11.000000
75%              2025-09-02 06:00:00    74.307500         15.000000
max              2026-01-04 00:00:00   798.010000         84.000000
std                              NaN   135.172962         12.370504

====================
PRESCRIPTIONS
====================

       duration_days     quantity                prescribed_date
count    3800.000000  3800.000000                           3800
mean       10.259211    17.315000  2025-02-25 10:14:39.157894656
min         3.000000     3.000000            2024-01-01 00:00:00
25%         5.000000     7.000000            2024-09-09 18:00:00
50%         7.000000    14.000000            2025-03-21 00:00:00
75%        14.000000    20.000000            2025-09-03 00:00:00
max        30.000000    90.000000            2025-12-31 00:00:00
std         8.013047    16.439252                            NaN

====================
DOCTORS
====================

       experience_years  consultation_fee            join_date
count          80.00000         80.000000                   80
mean           14.51250        113.353000  2017-05-08 23:24:00
min             2.00000         63.000000  2004-04-29 00:00:00
25%            10.75000         93.707500  2013-06-24 06:00:00
50%            14.00000        108.000000  2018-08-15 12:00:00
75%            17.25000        129.000000  2022-05-20 12:00:00
max            34.00000        222.500000  2023-09-14 00:00:00
std             7.02616         32.387732                  NaN

====================
DEPARTMENTS
====================

           floor  annual_budget
count  12.000000   1.200000e+01
mean    2.166667   2.725000e+06
std     1.267304   1.230761e+06
min     0.000000   1.000000e+06
25%     1.000000   1.875000e+06
50%     2.000000   2.550000e+06
75%     3.000000   3.425000e+06
max     4.000000   5.100000e+06

====================
ROOMS
====================

            floor  daily_rate    capacity
count  150.000000   150.00000  150.000000
mean     3.006667   260.70260    3.266667
std      1.411823   241.67164    2.272292
min      1.000000    82.96000    1.000000
25%      2.000000    93.62750    1.000000
50%      3.000000   179.17000    2.000000
75%      4.000000   319.79250    6.000000
max      5.000000   893.90000    6.000000

====================
MEDICINES
====================

       unit_price
count   63.000000
mean    19.253810
std     33.160091
min      1.790000
25%      6.155000
50%     10.480000
75%     15.545000
max    180.980000

In [17]:
patients = tables["patients"]

print("Total rows:", len(patients))
print("Unique patient IDs:", patients["patient_id"].nunique())
print("Duplicate patient IDs:", patients["patient_id"].duplicated().sum())

Total rows: 3400
Unique patient IDs: 3400
Duplicate patient IDs: 0

In [18]:
appointments = tables["appointments"]

print("Total rows:", len(appointments))
print("Unique appointment IDs:", appointments["appointment_id"].nunique())
print("Duplicate appointment IDs:", appointments["appointment_id"].duplicated().sum())

Total rows: 5500
Unique appointment IDs: 5500
Duplicate appointment IDs: 0

In [19]:
admissions = tables["admissions"]

print("Total rows:", len(admissions))
print("Unique admission_id:", admissions["admission_id"].nunique())
print("Duplicate admission_ids:", admissions["admission_id"].duplicated().sum())

Total rows: 2000
Unique admission_id: 2000
Duplicate admission_ids: 0

In [20]:
billing = tables["billing"]

print("Total rows:", len(billing))
print("Unique bill IDs:", billing["bill_id"].nunique())
print("Duplicate bill IDs:", billing["bill_id"].duplicated().sum())

Total rows: 6116
Unique bill IDs: 6116
Duplicate bill IDs: 0

In [21]:
lab_tests = tables["lab_tests"]

print("Total rows:", len(lab_tests))
print("Unique lab test IDs:", lab_tests["lab_test_id"].nunique())
print("Duplicate lab test IDs:", lab_tests["lab_test_id"].duplicated().sum())

Total rows: 3500
Unique lab test IDs: 3500
Duplicate lab test IDs: 0

In [22]:
prescriptions = tables["prescriptions"]

print("Total rows:", len(prescriptions))
print("Unique prescription IDs:", prescriptions["prescription_id"].nunique())
print("Duplicate prescription IDs:", prescriptions["prescription_id"].duplicated().sum())

Total rows: 3800
Unique prescription IDs: 3800
Duplicate prescription IDs: 0

In [23]:
doctors = tables["doctors"]

print("Total rows:", len(doctors))
print("Unique doctor IDs:", doctors["doctor_id"].nunique())
print("Duplicate doctor IDs:", doctors["doctor_id"].duplicated().sum())

Total rows: 80
Unique doctor IDs: 80
Duplicate doctor IDs: 0

In [24]:
patients = tables["patients"]

print("Total rows:", len(patients))
print("Unique patient IDs:", patients["patient_id"].nunique())
print("Duplicate patient IDs:", patients["patient_id"].duplicated().sum())

Total rows: 3400
Unique patient IDs: 3400
Duplicate patient IDs: 0

In [25]:
doctors = tables["doctors"]

print("Total rows:", len(doctors))
print("Unique doctor IDs:", doctors["doctor_id"].nunique())
print("Duplicate doctor IDs:", doctors["doctor_id"].duplicated().sum())

Total rows: 80
Unique doctor IDs: 80
Duplicate doctor IDs: 0

In [26]:
departments = tables["departments"]

print("Total rows:", len(departments))
print("Unique department IDs:", departments["department_id"].nunique())
print("Duplicate department IDs:", departments["department_id"].duplicated().sum())

Total rows: 12
Unique department IDs: 12
Duplicate department IDs: 0

In [27]:
rooms = tables["rooms"]

print("Total rows:", len(rooms))
print("Unique room IDs:", rooms["room_id"].nunique())
print("Duplicate room IDs:", rooms["room_id"].duplicated().sum())

Total rows: 150
Unique room IDs: 150
Duplicate room IDs: 0

In [28]:
medicines = tables["medicines"]

print("Total rows:", len(medicines))
print("Unique medicine IDs:", medicines["medicine_id"].nunique())
print("Duplicate medicine IDs:", medicines["medicine_id"].duplicated().sum())

Total rows: 63
Unique medicine IDs: 63
Duplicate medicine IDs: 0

In [29]:
invalid_patient_ids = appointments[
    ~appointments["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [30]:
invalid_doctor_ids = appointments[
    ~appointments["doctor_id"].isin(doctors["doctor_id"])
]

print("Invalid doctor IDs:", len(invalid_doctor_ids))

Invalid doctor IDs: 0

In [31]:
invalid_patient_ids = appointments[
    ~appointments["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [32]:
invalid_patient_ids = admissions[
    ~admissions["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [33]:
invalid_doctor_ids = admissions[
    ~admissions["doctor_id"].isin(doctors["doctor_id"])
]

print("Invalid doctor IDs:", len(invalid_doctor_ids))

Invalid doctor IDs: 0

In [34]:
invalid_department_ids = admissions[
    ~admissions["department_id"].isin(departments["department_id"])
]

print("Invalid department IDs:", len(invalid_department_ids))

Invalid department IDs: 0

In [35]:
invalid_patient_ids = admissions[
    ~admissions["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [36]:
invalid_patient_ids = billing[
    ~billing["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [37]:
invalid_appointment_ids = billing[
    billing["appointment_id"].notna() &
    ~billing["appointment_id"].isin(appointments["appointment_id"])
]

print("Invalid appointment IDs:", len(invalid_appointment_ids))

Invalid appointment IDs: 0

In [38]:
invalid_admission_ids = billing[
    billing["admission_id"].notna() &
    ~billing["admission_id"].isin(admissions["admission_id"])
]

print("Invalid admission IDs:", len(invalid_admission_ids))

Invalid admission IDs: 0

In [39]:
invalid_patient_ids = lab_tests[
    ~lab_tests["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [40]:
invalid_doctor_ids = lab_tests[
    ~lab_tests["doctor_id"].isin(doctors["doctor_id"])
]

print("Invalid doctor IDs:", len(invalid_doctor_ids))

Invalid doctor IDs: 0

In [41]:
invalid_appointment_ids = lab_tests[
    lab_tests["appointment_id"].notna() &
    ~lab_tests["appointment_id"].isin(appointments["appointment_id"])
]

print("Invalid appointment IDs:", len(invalid_appointment_ids))

Invalid appointment IDs: 0

In [42]:
invalid_admission_ids = lab_tests[
    lab_tests["admission_id"].notna() &
    ~lab_tests["admission_id"].isin(admissions["admission_id"])
]

print("Invalid admission IDs:", len(invalid_admission_ids))

Invalid admission IDs: 0

In [43]:
invalid_patient_ids = prescriptions[
    ~prescriptions["patient_id"].isin(patients["patient_id"])
]

print("Invalid patient IDs:", len(invalid_patient_ids))

Invalid patient IDs: 0

In [44]:
invalid_doctor_ids = prescriptions[
    ~prescriptions["doctor_id"].isin(doctors["doctor_id"])
]

print("Invalid doctor IDs:", len(invalid_doctor_ids))

Invalid doctor IDs: 0

In [45]:
invalid_appointment_ids = prescriptions[
    prescriptions["appointment_id"].notna() &
    ~prescriptions["appointment_id"].isin(appointments["appointment_id"])
]

print("Invalid appointment IDs:", len(invalid_appointment_ids))

Invalid appointment IDs: 0

In [46]:
invalid_admission_ids = prescriptions[
    prescriptions["admission_id"].notna() &
    ~prescriptions["admission_id"].isin(admissions["admission_id"])
]

print("Invalid admission IDs:", len(invalid_admission_ids))

Invalid admission IDs: 0

In [47]:
invalid_dates = admissions[
    admissions["discharge_date"] < admissions["admission_date"]
]

print("Discharge before admission:", len(invalid_dates))

Discharge before admission: 0

In [52]:
print(admissions.columns.tolist())

['admission_id', 'patient_id', 'doctor_id', 'department_id', 'room_id', 'admission_date', 'discharge_date', 'length_of_stay', 'admission_type', 'diagnosis', 'discharge_status', 'readmitted_within_30d']

In [53]:
invalid_los = admissions[
    admissions["length_of_stay"] <= 0
]

print("Invalid Length of Stay:", len(invalid_los))

Invalid Length of Stay: 0

In [54]:
invalid_registration = patients[
    patients["registration_date"] < patients["date_of_birth"]
]

print("Registration before Date of Birth:", len(invalid_registration))

Registration before Date of Birth: 132

In [55]:
display(invalid_registration[
    ["patient_id", "date_of_birth", "registration_date"]
].head(10))

    patient_id date_of_birth registration_date
3       P00004    2022-05-13        2020-08-02
6       P00007    2025-11-09        2023-04-26
20      P00021    2024-11-02        2021-05-05
51      P00052    2022-04-05        2020-09-18
63      P00064    2024-10-27        2022-06-04
88      P00089    2024-05-14        2020-06-08
103     P00104    2025-07-17        2025-03-18
115     P00116    2025-11-15        2021-12-23
132     P00133    2024-03-24        2023-10-19
151     P00152    2025-10-22        2024-01-12

In [58]:
reference_date = pd.Timestamp("2025-12-31")

calculated_age = (
    reference_date.year - patients["date_of_birth"].dt.year
    - ((patients["date_of_birth"].dt.month > reference_date.month)|
        ((patients["date_of_birth"].dt.month == reference_date.month) &
        (patients["date_of_birth"].dt.day > reference_date.day))))

age_mismatch = patients[
    patients["age"] != calculated_age
]

print("Age mismatches:", len(age_mismatch))

Age mismatches: 1

In [59]:
display(age_mismatch[["patient_id", "date_of_birth", "age"]])

     patient_id date_of_birth  age
2698     P02699    1976-01-01   50

In [60]:
invalid_wait_time = appointments[
    appointments["wait_time_min"] < 0
]

print("Negative Wait Time:", len(invalid_wait_time))

Negative Wait Time: 0

In [61]:
invalid_fee = appointments[
    appointments["consultation_fee"] < 0
]

print("Negative Consultation Fee:", len(invalid_fee))

Negative Consultation Fee: 0

In [62]:
amount_columns = [
    "total_amount",
    "insurance_covered",
    "patient_payable"
]

for col in amount_columns:
    print(col, "→", (billing[col] < 0).sum(), "negative values")

total_amount → 0 negative values
insurance_covered → 0 negative values
patient_payable → 0 negative values

In [63]:
invalid_rating = appointments[
    (appointments["satisfaction_rating"] < 1) |
    (appointments["satisfaction_rating"] > 5)
]

print("Invalid Satisfaction Ratings:", len(invalid_rating))

Invalid Satisfaction Ratings: 0

In [64]:
billing_mismatch = billing[
    ~(
        billing["total_amount"].round(2)
        == (
            billing["insurance_covered"] + billing["patient_payable"]
        ).round(2)
    )
]

print("Billing calculation mismatches:", len(billing_mismatch))

Billing calculation mismatches: 430

In [65]:
display(
    billing_mismatch[
        ["bill_id", "total_amount", "insurance_covered", "patient_payable"]
    ].head(10)
)

    bill_id  total_amount  insurance_covered  patient_payable
29   B00030       1283.88             857.88           425.99
33   B00034        617.74             311.94           305.81
56   B00057       1306.73            1154.10           152.64
63   B00064        182.97             151.09            31.87
67   B00068        869.06             751.35           117.72
211  B00212        276.06             147.87           128.18
212  B00213       2565.72            1320.47          1245.24
216  B00217        159.91              53.45           106.45
222  B00223       6126.35            4960.07          1166.29
244  B00245       6251.31            4834.07          1417.23

In [66]:
billing_difference = (
    billing["total_amount"]
    - billing["insurance_covered"]
    - billing["patient_payable"]
).abs()

print("Differences greater than ₹0.01:", (billing_difference > 0.01).sum())
print("Maximum difference:", billing_difference.max())

Differences greater than ₹0.01: 175
Maximum difference: 0.010000000001127773

In [67]:
payable_difference = (
    billing["patient_payable"]
    - (billing["total_amount"] - billing["insurance_covered"])
).abs()

print("Differences greater than ₹0.01:", (payable_difference > 0.01).sum())
print("Maximum difference:", payable_difference.max())

Differences greater than ₹0.01: 175
Maximum difference: 0.010000000001127773

In [68]:
invalid_readmission = admissions[
    ~admissions["readmitted_within_30d"].isin(["Yes", "No"])
]

print("Invalid readmission values:", len(invalid_readmission))

Invalid readmission values: 0

In [ ]:
Python Data Validation — Completed ✅
We have now validated:
- Primary keys and duplicates ✅
- Foreign-key relationships ✅
- Admission/discharge dates ✅
- Length of stay ✅
- Registration date vs DOB ⚠️ 132 anomalies
- Patient age vs DOB ⚠️ 1 mismatch
- Appointment wait time ✅
- Consultation fees ✅
- Billing amounts ✅
- Satisfaction ratings ✅
- Billing calculations ✅
- Patient payable calculations ✅
- Readmission flag values ✅
Final Python data-quality findings
Finding	Result	Action
Registration before DOB	132	Flag, don't modify
Age/DOB mismatch	1	Flag, don't modify
Other validation checks	Clean	No action


So Python profiling + data-quality validation is complete. 🎯

In [69]:
no_show_rate = (
    (appointments["status"] == "No-Show").sum()/ len(appointments)* 100)

print("Total Appointments:", len(appointments))
print("No-Show Appointments:", (appointments["status"] == "No-Show").sum())
print("Overall No-Show Rate:", round(no_show_rate, 2), "%")

Total Appointments: 5500
No-Show Appointments: 528
Overall No-Show Rate: 9.6 %

In [70]:
no_show_by_type = (
    appointments.groupby("appointment_type")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_type["no_show_rate"] = (
    no_show_by_type["no_shows"]
    / no_show_by_type["total_appointments"]
    * 100
)

display(no_show_by_type.sort_values("no_show_rate", ascending=False))

                  total_appointments  no_shows  no_show_rate
appointment_type
Routine Checkup                  892        98     10.986547
Follow-up                       2298       241     10.487380
New                             1888       189     10.010593
Emergency                        422         0      0.000000

In [71]:
no_show_by_dept = (
    appointments.groupby("department_id")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_dept["no_show_rate"] = (
    no_show_by_dept["no_shows"]
    / no_show_by_dept["total_appointments"]
    * 100
)

display(
    no_show_by_dept
    .sort_values("no_show_rate", ascending=False)
)

               total_appointments  no_shows  no_show_rate
department_id
D08                           301        36     11.960133
D03                           622        67     10.771704
D01                           893        95     10.638298
D12                           229        24     10.480349
D05                           869        90     10.356732
D06                           263        26      9.885932
D10                           331        30      9.063444
D02                           617        55      8.914100
D04                           519        45      8.670520
D11                           188        14      7.446809
D09                           339        24      7.079646
D07                           329        22      6.686930

In [72]:
display(
    departments[
        ["department_id", "department_name"]
    ]
)

   department_id          department_name
0            D01         General Medicine
1            D02                Emergency
2            D03               Cardiology
3            D04              Orthopedics
4            D05               Pediatrics
5            D06  Gynecology & Obstetrics
6            D07         Gastroenterology
7            D08              Pulmonology
8            D09                Neurology
9            D10                 Oncology
10           D11                      ENT
11           D12              Dermatology

In [73]:
no_show_by_dept = (
    no_show_by_dept
    .reset_index()
    .merge(
        departments[["department_id", "department_name"]],
        on="department_id",
        how="left"
    )
)

display(
    no_show_by_dept[
        ["department_id", "department_name",
         "total_appointments", "no_shows", "no_show_rate"]
    ]
    .sort_values("no_show_rate", ascending=False)
)

,department_id,department_name,total_appointments,no_shows,no_show_rate
7,D08,Pulmonology,301,36,11.960133
2,D03,Cardiology,622,67,10.771704
0,D01,General Medicine,893,95,10.638298
11,D12,Dermatology,229,24,10.480349
4,D05,Pediatrics,869,90,10.356732
5,D06,Gynecology & Obstetrics,263,26,9.885932
9,D10,Oncology,331,30,9.063444
1,D02,Emergency,617,55,8.914100
3,D04,Orthopedics,519,45,8.670520
10,D11,ENT,188,14,7.446809
8,D09,Neurology,339,24,7.079646
6,D07,Gastroenterology,329,22,6.686930

In [74]:
no_show_by_gender = (
    appointments
    .merge(
        patients[["patient_id", "gender"]],
        on="patient_id",
        how="left"
    )
    .groupby("gender")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_gender["no_show_rate"] = (
    no_show_by_gender["no_shows"]
    / no_show_by_gender["total_appointments"]
    * 100
)

display(no_show_by_gender)

        total_appointments  no_shows  no_show_rate
gender
Female                2877       272      9.454293
Male                  2623       256      9.759817

In [75]:
appointment_age = appointments.merge(
    patients[["patient_id", "age"]],
    on="patient_id",
    how="left"
)

appointment_age["age_group"] = pd.cut(
    appointment_age["age"],
    bins=[0, 18, 35, 50, 65, 100],
    labels=["0-18", "19-35", "36-50", "51-65", "66+"]
)

no_show_by_age = (
    appointment_age
    .groupby("age_group", observed=True)
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_age["no_show_rate"] = (
    no_show_by_age["no_shows"]
    / no_show_by_age["total_appointments"]
    * 100
)

display(no_show_by_age)

           total_appointments  no_shows  no_show_rate
age_group
0-18                      883        92     10.419026
19-35                     916        87      9.497817
36-50                    1480       126      8.513514
51-65                    1337       124      9.274495
66+                       815        93     11.411043

In [76]:
appointments["appointment_date"] = pd.to_datetime(
    appointments["appointment_date"]
)

appointments["day_of_week"] = appointments["appointment_date"].dt.day_name()

no_show_by_day = (
    appointments
    .groupby("day_of_week")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_day["no_show_rate"] = (
    no_show_by_day["no_shows"]
    / no_show_by_day["total_appointments"]
    * 100
)

day_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

no_show_by_day = no_show_by_day.reindex(day_order)

display(no_show_by_day)

             total_appointments  no_shows  no_show_rate
day_of_week
Monday                      963        90      9.345794
Tuesday                     960        91      9.479167
Wednesday                   936        90      9.615385
Thursday                    827        79      9.552600
Friday                      829        85     10.253317
Saturday                    628        60      9.554140
Sunday                      357        33      9.243697

In [77]:
appointments["wait_time_group"] = pd.cut(
    appointments["wait_time_min"],
    bins=[-1, 15, 30, 60, 120, float("inf")],
    labels=["0-15 min", "16-30 min", "31-60 min", "61-120 min", "120+ min"]
)

no_show_by_wait = (
    appointments
    .groupby("wait_time_group", observed=True)
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_wait["no_show_rate"] = (
    no_show_by_wait["no_shows"]
    / no_show_by_wait["total_appointments"]
    * 100
)

display(no_show_by_wait)

                 total_appointments  no_shows  no_show_rate
wait_time_group
0-15 min                       1284         0           0.0
16-30 min                      1454         0           0.0
31-60 min                      1186         0           0.0
61-120 min                      188         0           0.0
120+ min                          4         0           0.0

In [78]:
no_show_missing_wait = appointments[
    (appointments["status"] == "No-Show") &
    (appointments["wait_time_min"].isna())
]

print("No-shows with missing wait time:", len(no_show_missing_wait))

No-shows with missing wait time: 528

In [79]:
no_show_diagnosis = appointments[
    (appointments["status"] == "No-Show") &
    (appointments["diagnosis"].notna())
]

print("No-shows with diagnosis:", len(no_show_diagnosis))

No-shows with diagnosis: 0

In [80]:
appointments["month"] = appointments["appointment_date"].dt.to_period("M")

no_show_by_month = (
    appointments
    .groupby("month")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_month["no_show_rate"] = (
    no_show_by_month["no_shows"]
    / no_show_by_month["total_appointments"]
    * 100
)

display(no_show_by_month)

         total_appointments  no_shows  no_show_rate
month
2024-01                 184        17      9.239130
2024-02                 134        13      9.701493
2024-03                 149         9      6.040268
2024-04                 149        13      8.724832
2024-05                 145        17     11.724138
2024-06                 158        16     10.126582
2024-07                 206        16      7.766990
2024-08                 192        13      6.770833
2024-09                 221        19      8.597285
2024-10                 208        21     10.096154
2024-11                 194        25     12.886598
2024-12                 243        26     10.699588
2025-01                 240        20      8.333333
2025-02                 202        20      9.900990
2025-03                 229        20      8.733624
2025-04                 231        15      6.493506
2025-05                 213        27     12.676056
2025-06                 236        26     11.016949
2025-07                 283        28      9.893993
2025-08                 348        24      6.896552
2025-09                 328        37     11.280488
2025-10                 322        37     11.490683
2025-11                 300        25      8.333333
2025-12                 385        44     11.428571

In [81]:
appointments["year"] = appointments["appointment_date"].dt.year

no_show_by_year = (
    appointments
    .groupby("year")
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

no_show_by_year["no_show_rate"] = (
    no_show_by_year["no_shows"]
    / no_show_by_year["total_appointments"]
    * 100
)

display(no_show_by_year)

      total_appointments  no_shows  no_show_rate
year
2024                2183       205      9.390747
2025                3317       323      9.737715

In [82]:
dept_age = (
    appointment_age
    .groupby(["department_id", "age_group"], observed=True)
    .agg(
        total_appointments=("appointment_id", "count"),
        no_shows=("status", lambda x: (x == "No-Show").sum())
    )
)

dept_age["no_show_rate"] = (
    dept_age["no_shows"]
    / dept_age["total_appointments"]
    * 100
)

display(
    dept_age
    .sort_values("no_show_rate", ascending=False)
    .head(15)
)

                         total_appointments  no_shows  no_show_rate
department_id age_group
D06           66+                        13         3     23.076923
D03           0-18                       10         2     20.000000
D04           0-18                       10         2     20.000000
D08           66+                        52        10     19.230769
D06           51-65                      32         6     18.750000
D12           66+                        33         5     15.151515
D01           0-18                       14         2     14.285714
D03           66+                       155        22     14.193548
D08           19-35                      51         7     13.725490
              51-65                      97        13     13.402062
D01           51-65                     263        35     13.307985
D10           36-50                      82        10     12.195122
              66+                        79         9     11.392405
D01           66+                       125        14     11.200000
D07           0-18                        9         1     11.111111

In [83]:
dept_age = (
    dept_age
    .reset_index()
    .merge(
        departments[["department_id", "department_name"]],
        on="department_id",
        how="left"
    )
)

display(
    dept_age[
        [
            "department_id",
            "department_name",
            "age_group",
            "total_appointments",
            "no_shows",
            "no_show_rate"
        ]
    ]
    .sort_values("no_show_rate", ascending=False)
    .head(15)
)

,department_id,department_name,age_group,total_appointments,no_shows,no_show_rate
24,D06,Gynecology & Obstetrics,66+,13,3,23.076923
10,D03,Cardiology,0-18,10,2,20.000000
15,D04,Orthopedics,0-18,10,2,20.000000
34,D08,Pulmonology,66+,52,10,19.230769
23,D06,Gynecology & Obstetrics,51-65,32,6,18.750000
54,D12,Dermatology,66+,33,5,15.151515
0,D01,General Medicine,0-18,14,2,14.285714
14,D03,Cardiology,66+,155,22,14.193548
31,D08,Pulmonology,19-35,51,7,13.725490
33,D08,Pulmonology,51-65,97,13,13.402062
3,D01,General Medicine,51-65,263,35,13.307985
42,D10,Oncology,36-50,82,10,12.195122
44,D10,Oncology,66+,79,9,11.392405
4,D01,General Medicine,66+,125,14,11.200000
25,D07,Gastroenterology,0-18,9,1,11.111111